from .base_action import *
from .compose_action import *
from .common_action import *
from .calculator_action import *
from .powerpoint_action import *
from .microsoft_edge_action import *
from .amazon_action import *
from .notepad_action import *
from .bing_search_action import *
from .vlc_action import *
from .chrome_actions import *
from .clock_action import *
from .windows_settings_action import *
from .vs_code_action import *
from .youtube_action import *
from .paint_action import *
from .file_explorer_action import *
from .excel_action import *
from .word_action import *