#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_list.py

Generate a list where each element is generated by a specified generator function.
"""

from typing import Callable, Dict, Any, List, Union
import random


def generate_list(
    element_generator: str,
    generator_arguments: Dict[str, Any],
    min_length: int = 1,
    max_length: int = 10,
    allow_duplicates: bool = True,
    return_as_string: bool = False,
    separator: str = ",",
    **kwargs
) -> Union[List[Any], str]:
    """
    Generate a list where each element is created by calling the specified generator function.
    
    Args:
        element_generator (str): The name of the generator function to use for each element.
                                 This should be a key in the ARGUMENT_GENERATORS dictionary.
        generator_arguments (Dict[str, Any]): Arguments to pass to the generator function for each element.
        min_length (int): Minimum number of elements in the list (default: 1).
        max_length (int): Maximum number of elements in the list (default: 10).
        allow_duplicates (bool): Whether to allow duplicate elements in the list (default: True).
                                 If False, the generator will keep trying until unique elements are found.
        return_as_string (bool): Whether to return the list as a string (default: False).
        separator (str): Separator to use when joining elements into a string (default: ",").
                        Only used when return_as_string=True.
        **kwargs: Additional arguments (ignored).
    
    Returns:
        Union[List[Any], str]: A list of generated elements, or a string if return_as_string=True.
    
    Example:
        # Generate a list of 3-5 random numbers
        generate_list(
            element_generator="generate_random_number",
            generator_arguments={"min_value": 0, "max_value": 100},
            min_length=3,
            max_length=5
        )
        
        # Generate a list of 2-4 unique strings returned as a semicolon-separated string
        generate_list(
            element_generator="generate_string",
            generator_arguments={"min_length": 5, "max_length": 10},
            min_length=2,
            max_length=4,
            allow_duplicates=False,
            return_as_string=True,
            separator="; "
        )
    """
    # Import the ARGUMENT_GENERATORS dictionary to access generator functions
    from . import ARGUMENT_GENERATORS
    
    # Validate that the generator exists
    if element_generator not in ARGUMENT_GENERATORS:
        raise ValueError(f"Unknown generator function: {element_generator}. "
                        f"Available generators: {list(ARGUMENT_GENERATORS.keys())}")
    
    # Get the generator function
    generator_func = ARGUMENT_GENERATORS[element_generator]
    
    # Determine the list length
    list_length = random.randint(min_length, max_length)
    
    # Generate the list
    result = []
    seen = set() if not allow_duplicates else None
    max_attempts = list_length * 100  # Prevent infinite loops
    attempts = 0
    
    while len(result) < list_length and attempts < max_attempts:
        attempts += 1
        # Call the generator function with the provided arguments
        element = generator_func(**generator_arguments)
        
        if allow_duplicates:
            result.append(element)
        else:
            # Convert to string for hashability if needed
            element_key = str(element) if not isinstance(element, (str, int, float, tuple)) else element
            if element_key not in seen:
                seen.add(element_key)
                result.append(element)
    
    # Warning if we couldn't generate enough unique elements
    if not allow_duplicates and len(result) < list_length:
        import warnings
        warnings.warn(
            f"Could not generate {list_length} unique elements. "
            f"Only {len(result)} unique elements were generated after {max_attempts} attempts."
        )
    
    # Return as string if requested
    if return_as_string:
        return separator.join(str(elem) for elem in result)
    
    return result
